### ISSUE TITLE
Про порт забыл

### ISSUE THREAD

**Issue by Antibrag** [Masonchiiik/CalcGo#1]
Ты забыл при запуске сервера, указать порт. Собственно поэтому и сервак не работает:

![изображение](https://github.com/user-attachments/assets/91eb541a-e40b-460a-a759-33b7814ed707)
![изображение](https://github.com/user-attachments/assets/c31f4b28-59b9-4644-a8dc-e3ccd4f86705)

**Comment by Masonchiiik** [comment]
не знаю, но вообще так и задумано XD, просто у тебя видимо дефолт порт занят (потому что у меня всё работает)
но замечание хоршее, пофикшу

**Comment by Masonchiiik** [comment]
Пофиксил
